files: ^app/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: fix-encoding-pragma
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.253'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        stages: [commit]