# docker-compose.prod.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - WORKERS_PER_CORE=1
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
    ports:
      - 8000:80
