"""Add embeddings

Revision ID: 01102581a76f
Revises: ef670c9c5b50
Create Date: 2023-04-10 20:22:44.061578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01102581a76f"
down_revision = "ef670c9c5b50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("sentence_id", sa.Integer(), nullable=True),
        sa.Column("model_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vector", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.ForeignKeyConstraint(
            ["sentence_id"],
            ["sentences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("embeddings")
    # ### end Alembic commands ###
