"""add sentiments table

Revision ID: af0f00fe2ef9
Revises: 01102581a76f
Create Date: 2023-05-31 20:06:53.110512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af0f00fe2ef9'
down_revision = '01102581a76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tokenizer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('prediction_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('documents_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('red_lines', 'predicted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_lines', 'predicted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents_metadata', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('sentiments')
    # ### end Alembic commands ###
