"""New schema

Revision ID: ebc60714101b
Revises: 
Create Date: 2022-05-01 14:33:28.870853

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebc60714101b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_id'), 'metadata', ['id'], unique=False)
    op.create_table('features',
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('feature_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['metadata.id'], ),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index(op.f('ix_features_feature_id'), 'features', ['feature_id'], unique=False)
    op.create_table('texts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_texts_id'), 'texts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_texts_id'), table_name='texts')
    op.drop_table('texts')
    op.drop_index(op.f('ix_features_feature_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_metadata_id'), table_name='metadata')
    op.drop_table('metadata')
    # ### end Alembic commands ###
