"""turn off default indexing of all columns

Revision ID: ed397540fa48
Revises: 1515436d6989
Create Date: 2021-12-14 21:41:20.748426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ed397540fa48'
down_revision = '1515436d6989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_speeches_URL', table_name='speeches')
    op.drop_index('ix_speeches_category', table_name='speeches')
    op.drop_index('ix_speeches_created_at', table_name='speeches')
    op.drop_index('ix_speeches_date', table_name='speeches')
    op.drop_index('ix_speeches_text', table_name='speeches')
    op.drop_index('ix_speeches_title', table_name='speeches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_speeches_title', 'speeches', ['title'], unique=False)
    op.create_index('ix_speeches_text', 'speeches', ['text'], unique=False)
    op.create_index('ix_speeches_date', 'speeches', ['date'], unique=False)
    op.create_index('ix_speeches_created_at', 'speeches', ['created_at'], unique=False)
    op.create_index('ix_speeches_category', 'speeches', ['category'], unique=False)
    op.create_index('ix_speeches_URL', 'speeches', ['URL'], unique=False)
    # ### end Alembic commands ###
